### ISSUE TITLE
Middleware Response Overrides Default "Route Not Registered" Error in Gofr Framework

### ISSUE THREAD

**Issue by shashank-zopsmart** [gofr-dev/gofr#1297]
When using the Gofr framework for REST API development, an unregistered route normally triggers the framework to return a "Route Not Registered" error response. However, if a middleware is injected, the middleware is executed first, resulting in its response being returned instead of the default "Route Not Registered" error. This behavior causes confusion and may not align with expected behavior for handling unregistered routes.

- Steps to Reproduce:
  - Register a middleware for all incoming requests.
  - Send a request to an unregistered route.
  - Observe that the middleware response is returned instead of the expected "Route Not Registered" error.

- Expected Behavior: The framework should prioritize returning the "Route Not Registered" error for unregistered routes, bypassing middleware execution where applicable.

**Comment by Umang01-hash** [comment]
@shashank-zopsmart Thank you for raising this concern. 

The behavior you observed, where the middleware response is returned instead of the `Route Not Registered` error, is indeed the **intended functionality of the GoFr framework**. This design ensures that middleware can effectively handle and respond to requests before they reach the route handling logic. 

Here are a few key points to consider:

1. **Middleware Priority**: Middleware is designed to intercept and potentially handle requests before they reach the route handlers. This allows for important tasks such as authentication, logging, and request modification to occur early in the request lifecycle.

2. **Security Considerations**: By allowing middleware to handle requests, we can ensure that sensitive information about route existence is not exposed. For example, if an authentication middleware detects an invalid token, it can respond immediately without revealing whether the requested route exists.

3. **Framework Design**: The framework cannot override a response that has already been returned by middleware. Once a middleware returns a response, the request does not proceed further down the chain, including to the route handling logic.

This separation of concerns is crucial for maintaining a secure and modular application architecture. If you have specific use cases or scenarios where this behavior causes issues, we would be happy to discuss them further and explore potential solutions.

Thank you for your understanding and for using GoFr.
