### ISSUE TITLE
Enhance publisher

### ISSUE THREAD

**Issue by PapePathe** [gofr-dev/gofr#538]
Currently the publisher only supports setting a message. It would be nice to have support for setting message key and headers.
Something like `err = ctx.GetPublisher().Publish(ctx, pubsub.PublishRequest{ Topic: "products", Message: msg, Key: "a key"})`.

I hacked breaking code changes on my fork this weekend and wanted to discuss:
-  if this is something you would like to support ?
- how should be approach it so that we still support the old api ?

**Comment by Umang01-hash** [comment]
@PapePathe gofr's publisher that you get from `ctx.GetPublisher()` is a generic implementation for publishing to different pub-sub backends like **kafka, mqtt, gcp** etc. Setting up of message key and headers is something relavant to kafka only not to other pub-sub backends. 

`if this is something you would like to support ?` : Yes, we are not bounded by any datasource.

`how should be approach it so that we still support the old api ?`
To have a functionality specific to kafka or any other backend, user can extend the functionality, similar to how we have extended for mongo.

we have defined it interface and methods in gofr : https://github.com/gofr-dev/gofr/blob/development/pkg/gofr/datasource/mongo.go
and its implementation exists in a different repo : https://github.com/vipul-rawat/gofr-mongo

Such that those who don't want it, will not have to get it as a dependency.

**Comment by PapePathe** [comment]
Thanks for the quick reply. I will study the mongo example and go from there

**Comment by PapePathe** [comment]
I am just curious how the mongo example can be integrated on an existing app

**Comment by Umang01-hash** [comment]
@PapePathe sure here is the mongo example : https://github.com/vipul-rawat/using-mongo
