### ISSUE TITLE
Default and Overridable Request Timeout

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/gofr#600]
Currently, request waits for 30 seconds before timing out, which should be less to about 5 seconds or user should be able to override.

<img width="635" alt="image" src="https://github.com/gofr-dev/gofr/assets/44036979/16e9aab4-61a7-433b-a281-a8a2d8cbf058">

**Comment by KedarisettiSreeVamsi** [comment]
Hi @Umang01-hash, I have just gone through the PR and I think we can use the context itself to set a timeout rather than explicitly mentioning a timeout parameter.

I am linking to a video from one of the channel where he mentioned that using context timeout is better than using a explicit timeout. Sorry if it is not a good suggestion.

Link: https://youtu.be/PCgnBCE-N8I?si=zEY19aawdKC4EbCb

Checkout after 13 minutes and 14 seconds.

**Comment by Umang01-hash** [comment]
> Hi @Umang01-hash, I have just gone through the PR and I think we can use the context itself to set a timeout rather than explicitly mentioning a timeout parameter for the function.
> 
> I am linking to a video from one of the channel where he mentioned that using context timeout is better than using a explicit timeout. Sorry if it is not a good suggestion.
> 
> Link: https://youtu.be/PCgnBCE-N8I?si=zEY19aawdKC4EbCb
> 
> Checkout after 13 minutes and 14 seconds.

Surely @KedarisettiSreeVamsi I was also planning to use context timeouts after the initial implementation of server timeout. Will update the code. Thanks for the video!!
