### ISSUE TITLE
Unable to subscribe messages while using Google Pubsub

### ISSUE THREAD

**Issue by Suhas-zs** [gofr-dev/gofr#88]
- Currently, we are able to publish messages successfully, but the subscriber is consuming the only the first message whenever we start a server.

**Comment by VipulSharma1999** [comment]
It's not a bug @Suhas-zs. You might be using: https://github.com/gofr-dev/gofr/blob/development/pkg/datastore/pubsub/google/google.go#L210
What it does is - consume a message and return that message. It's expected behaviour as of now, maybe will have to extend this to consume all the messages till the point we interrupt the program, something like Kafka.
https://github.com/gofr-dev/gofr/blob/development/pkg/datastore/pubsub/google/google.go#L243
